apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-html
data:
  index.html: |
    <html>
      <body style="font-family: Arial">
        <h1>NGINX via Kubernetes</h1>
        <p>Served by pod: <b>$HOSTNAME</b></p>
      </body>
    </html>
